### PR TITLE
Fix bug, cannot close the quickrun window if it is the last one.

### PR DESCRIPTION
**Pull request by QMonkey**

### CODE REVIEW

**Comment by thinca** [comment]
This is intentional.
I think it's dangerous that Vim is quitted with `q`.
How do you think?

**Comment by QMonkey** [comment]
In my opinion, nothing dangerous with ```quit```, because ```quit``` will fail when changes have been made. Usually, it doesn't make sense to change the content of quickrun. Therefore, it's usually same case for ```quit``` and ```close```, unless there is only one window left.

**Comment by thinca** [comment]
>  because quit will fail when changes have been made. 

quickrun's buffer is not set `'modified'` flag.  So you can close by `:quit` without error.
And, you will lost the result of quickrun.  `q` is easy operation.  I think this is dangerous.

If you want, you can overwrite the default mapping:

```vim
augroup vimrc-quickrun
  autocmd!
  autocmd FileType quickun nnoremap <buffer> q <C-w>q
augroup END
```

**Comment by QMonkey** [comment]
> If you want, you can overwrite the default mapping:
```vim
augroup vimrc-quickrun
  autocmd!
  autocmd FileType quickun nnoremap <buffer> q <C-w>q
augroup END
```

It doesn't work.

**Comment by thinca** [comment]
Sorry, it's a typo. `s/quickun/quickrun/`

```vim
augroup vimrc-quickrun
  autocmd!
  autocmd FileType quickrun nnoremap <buffer> q <C-w>q
augroup END
```

**Comment by QMonkey** [comment]
Thanks!

**Pull request closed without merging**
